"use client";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Box, ChartNoAxesCombined, Code2, Focus, Heart, Layers3, Network, Target, UsersRound, Zap, type LucideIcon } from "lucide-react";
import Image from "next/image";
import { useRef, useState, type PointerEvent } from "react";
import { ConnectedPractice3D } from "@/components/about/ConnectedPractice3D";

type Discipline = { name: string; description: string; status: string; icon: LucideIcon };
const disciplines: readonly Discipline[] = [
  { name: "Strategy", description: "Find the direction.", status: "Direction connected", icon: Target },
  { name: "Product", description: "Shape the experience.", status: "Product system connected", icon: Box },
  { name: "Engineering", description: "Build dependable foundations.", status: "Engineering connected", icon: Code2 },
  { name: "Automation", description: "Connect the workflow.", status: "Workflow connected", icon: Zap },
  { name: "Care", description: "Keep the system evolving.", status: "Evolution connected", icon: Heart },
] as const;
const values = [
  { title: "One connected team", copy: "Aligned around outcomes and long-term value.", icon: UsersRound },
  { title: "Systems that scale", copy: "Built for change, ready for what’s next.", icon: Layers3 },
  { title: "Impact that lasts", copy: "Thoughtful design. Solid engineering. Real results.", icon: ChartNoAxesCombined },
] as const;
const principles = [
  { title: "Clear by design", copy: "Make complex systems easier to understand and operate.", micro: "01 / Clarity", icon: Focus },
  { title: "Connected by default", copy: "Reduce unnecessary hand-offs across disciplines.", micro: "02 / Connection", icon: Network },
  { title: "Built to evolve", copy: "Create foundations that can adapt as the business changes.", micro: "03 / Evolution", icon: Layers3 },
] as const;
const paths = ["M165 105 C270 140 330 210 430 275","M710 100 C610 150 550 220 455 275","M750 290 C625 290 555 285 460 282","M690 455 C590 395 530 330 455 292","M145 440 C265 385 330 325 435 290"];
const ease = [0.22, 1, 0.36, 1] as const;

export function About() {
  const [active, setActive] = useState(2); const [practiceActive, setPracticeActive] = useState(1); const visualRef = useRef<HTMLDivElement>(null); const reduceMotion = useReducedMotion();
  function handleMove(event: PointerEvent<HTMLDivElement>) { const visual = visualRef.current; if (!visual || event.pointerType === "touch" || reduceMotion) return; const rect = visual.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width - .5; const y = (event.clientY - rect.top) / rect.height - .5; visual.style.setProperty("--about-ry", `${x * 3}deg`); visual.style.setProperty("--about-rx", `${y * -2}deg`); visual.style.setProperty("--about-y", `${y * -8}px`); }
  return <section className="v3-about about-final" id="about"><div className="v3-shell">
    <div className="about-final__intro"><motion.div initial={reduceMotion ? false : { opacity: 0, y: 15 }} transition={{ duration: .55, ease }} viewport={{ once: true }} whileInView={{ opacity: 1, y: 0 }}><p className="v3-kicker">The Growblic practice</p><h2>One team.<br />Connected by<br />the system<span>.</span></h2><p className="about-final__support">We bring strategy, product thinking, engineering, automation, and ongoing care together in one connected digital practice.</p></motion.div><motion.div className="about-final__statement" initial={reduceMotion ? false : { opacity: 0, y: 14 }} transition={{ delay: .12, duration: .55, ease }} viewport={{ once: true }} whileInView={{ opacity: 1, y: 0 }}><h3>Growblic brings strategy, product thinking, engineering, automation and ongoing care into one connected digital practice.</h3><p>We design and build digital systems that are simpler to run, easier to evolve, and built to create lasting impact.</p><div className="about-final__values">{values.map(({ title, copy, icon: Icon }, index) => <motion.article initial={reduceMotion ? false : { opacity: 0, y: 8 }} key={title} transition={{ delay: .2 + index * .07, duration: .4, ease }} viewport={{ once: true }} whileInView={{ opacity: 1, y: 0 }}><span><Icon size={20} /></span><div><strong>{title}</strong><small>{copy}</small></div></motion.article>)}</div></motion.div></div>
    <div className="about-final__experience"><div className="about-final__selector" role="tablist" aria-label="Growblic practice disciplines">{disciplines.map((discipline, index) => { const Icon = discipline.icon; return <motion.button aria-controls="about-campus" aria-selected={active === index} className={active === index ? "is-active" : ""} initial={reduceMotion ? false : { opacity: 0, x: -8 }} key={discipline.name} onClick={() => setActive(index)} role="tab" transition={{ delay: index * .055, duration: .4, ease }} type="button" viewport={{ once: true }} whileInView={{ opacity: 1, x: 0 }}><span>0{index + 1}</span><i><Icon size={19} /></i><div><strong>{discipline.name}</strong><small>{discipline.description}</small></div><ArrowRight size={15} /></motion.button>; })}</div>
      <motion.div className="about-final__campus" id="about-campus" initial={reduceMotion ? false : { opacity: 0, scale: 1.025, y: 18 }} onPointerLeave={() => visualRef.current?.removeAttribute("style")} onPointerMove={handleMove} ref={visualRef} role="tabpanel" transition={{ duration: .78, ease }} viewport={{ amount: .2, once: true }} whileInView={{ opacity: 1, scale: 1, y: 0 }}><div className="about-final__image"><Image alt="Growblic connected digital practice campus" fill sizes="(max-width: 960px) 100vw, 62vw" src="/images/growblic-about-campus-v2.png" /></div><div className="about-final__texture" /><svg className="about-final__paths" viewBox="0 0 900 540" preserveAspectRatio="none" aria-hidden="true">{paths.map((path, index) => <path className={active === index ? "is-active" : ""} d={path} key={path} />)}<circle r="4"><animateMotion dur="5.5s" path={paths[active]} repeatCount="indefinite" /></circle></svg><div className="about-final__modules">{disciplines.map((discipline, index) => { const Icon = discipline.icon; return <button aria-label={`Select ${discipline.name}`} aria-pressed={active === index} className={`campus-module campus-module-${index + 1}${active === index ? " is-active" : ""}`} key={discipline.name} onClick={() => setActive(index)} type="button"><Icon size={15} /><span><strong>{discipline.name}</strong><small>{discipline.description}</small></span><i /></button>; })}</div><div className="about-final__brand"><strong>Growblic</strong><span>{disciplines[active].status}</span><i /></div></motion.div>
    </div>
    <motion.div className="about-final__principles" initial="hidden" variants={{ hidden: {}, visible: { transition: { staggerChildren: .05 } } }} viewport={{ amount: .25, once: true }} whileInView="visible"><div className="about-final__principle-line" aria-hidden="true"><i /><i /><i /><b /></div>{principles.map(({ title, copy, micro, icon: Icon }, index) => <motion.article key={title} variants={reduceMotion ? undefined : { hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0, transition: { duration: .42, ease } } }}><header><span>0{index + 1}</span><i><Icon size={18} /></i></header><div><h3>{title}</h3><p>{copy}</p></div><small>{micro}</small></motion.article>)}</motion.div>
    <motion.section aria-label="Growblic connected digital practice" className="about-connected-practice-real" initial={reduceMotion ? false : { opacity: 0, scale: .98, y: 18 }} transition={{ duration: .82, ease }} viewport={{ amount: .18, once: true }} whileInView={{ opacity: 1, scale: 1, y: 0 }}><div className="about-connected-practice-real__copy"><div className="about-connected-practice-real__eyebrow"><p>Growblic / Our practice</p><span>Connected practice / 01—05</span></div><h3>Less hand-off.<br />More<br />Connection<i>.</i></h3><p className="about-connected-practice-real__support">Strategy, product, engineering, automation and care work better when they operate as one system.</p><div className="about-connected-practice-real__selector" role="tablist" aria-label="Connected practice disciplines">{disciplines.map((discipline,index)=>{const Icon=discipline.icon;return <button aria-selected={practiceActive===index} className={practiceActive===index?"is-active":""} key={discipline.name} onClick={()=>setPracticeActive(index)} role="tab" type="button"><span>0{index+1}</span><i><Icon size={17} /></i><strong>{discipline.name}</strong><ArrowRight size={15} /></button>})}</div></div><div className="about-connected-practice-real__panel"><div className="about-connected-practice-real__status"><span>Connected system / 0{practiceActive+1}</span><b>System online <i /></b></div><div className="about-connected-practice-real__canvas"><ConnectedPractice3D active={practiceActive} reducedMotion={Boolean(reduceMotion)} /></div><div className="about-connected-practice-real__fallback"><Image alt="Growblic connected practice with strategy, product, engineering, automation and care" height={1086} sizes="100vw" src="/images/more_connection_one_system.png" width={1448} /></div></div></motion.section>
    <motion.a className="about-final__next" href="#contact" initial={reduceMotion ? false : { opacity: 0, y: 8 }} transition={{ delay: .2, duration: .45, ease }} viewport={{ once: true }} whileInView={{ opacity: 1, y: 0 }}><span><small>Next / 07</small><b>Contact</b></span><i aria-hidden="true"><b /></i><strong>Let’s build what comes next. <ArrowRight size={17} /></strong></motion.a>
  </div></section>;
}
