"use client";
import { ArrowUpRight } from "lucide-react";
import { Logo } from "@/components/ui/Logo";
import { SectionReveal } from "@/components/animation/SectionReveal";
import { navigationItems } from "@/data/navigation";

export function Contact() { return <section className="v3-contact" id="contact"><div className="v3-shell v3-contact__grid"><SectionReveal className="v3-contact__intro"><p className="v3-kicker">Start a project</p><h2>Have a problem<br />worth building<br />around?</h2><p>Tell us what needs to work.<br />We&apos;ll help shape the system.</p></SectionReveal><SectionReveal delay={80}><form className="v3-form" onSubmit={event=>event.preventDefault()}><div><label>Name<input autoComplete="name" name="name" required /></label><label>Company<input autoComplete="organization" name="company" required /></label><label>Email<input autoComplete="email" name="email" required type="email" /></label><label>Phone<input autoComplete="tel" name="phone" type="tel" /></label><label>Project type<select defaultValue="" name="projectType" required><option disabled value="">Select type</option><option>New digital product</option><option>Existing system improvement</option><option>Automation initiative</option><option>Ongoing partnership</option></select></label><label>Services<select defaultValue="" name="services" required><option disabled value="">Select service</option><option>AI &amp; Automation</option><option>Web Platforms</option><option>Mobile Applications</option><option>SaaS Products</option><option>Education Technology</option><option>Cybersecurity</option><option>Digital Growth</option><option>Growblic Care</option></select></label><label>Budget<select defaultValue="" name="budget"><option value="">Not decided yet</option><option>INR 1L - 5L</option><option>INR 5L - 15L</option><option>INR 15L+</option></select></label><label>Preferred contact<select defaultValue="Email" name="contactMethod"><option>Email</option><option>Phone</option><option>Video call</option></select></label></div><label>Project description<textarea name="description" placeholder="What needs to work better?" required rows={4}/></label><button type="submit">Start the conversation <ArrowUpRight aria-hidden="true" size={18}/></button><small>Frontend enquiry form. No message is sent until a secure integration is connected.</small></form></SectionReveal></div>
  <footer className="v3-footer"><div className="v3-shell"><div className="v3-footer__brand"><Logo/><p>Digital systems behind modern business.</p></div><nav aria-label="Footer navigation">{navigationItems.slice(1).map(item=><a href={item.href} key={item.href}>{item.label}</a>)}</nav><a className="v3-footer__top" href="#home">Back to top ↑</a><div className="v3-footer__bottom"><span>© {new Date().getFullYear()} Growblic</span><span>Privacy</span><span>Terms</span><span>India / Worldwide</span></div></div></footer>
  </section>; }
