"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Blocks, Compass, PenTool, Rocket, Sparkles, type LucideIcon } from "lucide-react";
import { useRef, useState, type PointerEvent } from "react";

type Step = { title: string; description: string; micro: string; bullets: readonly string[]; nodes: readonly [string, string, string]; icon: LucideIcon };
const steps: readonly Step[] = [
  { title: "Discover", description: "Find the real problem and define what success must mean.", micro: "01 / Clarity", bullets: ["Problem framing", "User insight", "Success definition"], nodes: ["Signals", "Discovery", "Direction"], icon: Compass },
  { title: "Design", description: "Shape the experience, system and technical direction.", micro: "02 / Direction", bullets: ["Experience architecture", "System direction", "Prototype validation"], nodes: ["Signal map", "Design", "Operational value"], icon: PenTool },
  { title: "Build", description: "Deliver in focused cycles with quality visible throughout.", micro: "03 / Delivery", bullets: ["Iterative delivery", "Quality visibility", "Engineering alignment"], nodes: ["Approved design", "Engineering", "Working product"], icon: Blocks },
  { title: "Launch", description: "Release with confidence and operational foundations in place.", micro: "04 / Release", bullets: ["Release readiness", "Deployment coordination", "Operational foundations"], nodes: ["Release candidate", "Launch", "Live system"], icon: Rocket },
  { title: "Grow & Care", description: "Support and evolve the system as the business changes.", micro: "05 / Evolution", bullets: ["Monitoring", "Optimisation", "Product evolution"], nodes: ["Live signals", "Care", "Continuous value"], icon: Sparkles },
];
const ease = [0.22, 1, 0.36, 1] as const;

export function Work() {
  const [active, setActive] = useState(1); const visualRef = useRef<HTMLDivElement>(null); const reduceMotion = useReducedMotion(); const step = steps[active]; const ActiveIcon = step.icon;
  function handleMove(event: PointerEvent<HTMLDivElement>) { const panel = visualRef.current; if (!panel || event.pointerType === "touch" || reduceMotion) return; const rect = panel.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width - .5; const y = (event.clientY - rect.top) / rect.height - .5; panel.style.setProperty("--work-ry", `${x * 4}deg`); panel.style.setProperty("--work-rx", `${y * -3}deg`); }
  return <section className="v3-work" id="work"><div className="v3-shell">
    <div className="v3-work__heading"><motion.div initial={reduceMotion ? false : { opacity: 0, y: 16 }} viewport={{ once: true }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: .58, ease }}><p className="v3-kicker">How we work</p><h2>From problem<br />to product<span>.</span></h2></motion.div><motion.p initial={reduceMotion ? false : { opacity: 0, y: 14 }} viewport={{ once: true }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: .12, duration: .58, ease }}>One connected path from strategic clarity to a system that performs in the real world.</motion.p></div>
    <div className="v3-work-journey-label"><span>Product delivery system / 01—05</span><i /><span>Select a phase</span></div>
    <motion.div className="v3-work-rail" initial="hidden" role="tablist" aria-label="Growblic delivery process" style={{ "--route-progress": `${(active + 1) * 20}%` } as React.CSSProperties} variants={{ hidden: {}, visible: { transition: { staggerChildren: .06 } } }} viewport={{ once: true, amount: .2 }} whileInView="visible"><svg className="v3-work-route" viewBox="0 0 1200 120" preserveAspectRatio="none" aria-hidden="true"><path d="M40 66 C150 22 250 98 330 58 S520 28 610 66 S800 95 880 55 S1060 26 1160 62" /><path className="route-active" pathLength="100" d="M40 66 C150 22 250 98 330 58 S520 28 610 66 S800 95 880 55 S1060 26 1160 62" /><circle r="4"><animateMotion dur="7s" repeatCount="indefinite" path="M40 66 C150 22 250 98 330 58 S520 28 610 66 S800 95 880 55 S1060 26 1160 62" /></circle></svg>{steps.map((item, index) => { const StepIcon = item.icon; return <motion.button aria-controls="work-detail" aria-selected={active === index} className={active === index ? "is-active" : ""} key={item.title} onClick={() => setActive(index)} role="tab" type="button" variants={{ hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0, transition: { duration: .5, ease } } }}><div><span>0{index + 1}</span><StepIcon size={19} /></div><h3>{item.title}</h3><p>{item.description}</p><small>{item.micro}</small><i /></motion.button>; })}</motion.div>
    <div className="v3-work-detail"><div className="v3-work-system" onPointerLeave={() => visualRef.current?.removeAttribute("style")} onPointerMove={handleMove} ref={visualRef}><div className="v3-work-system__grid" /><svg className="v3-work-system__connections" viewBox="0 0 800 500" preserveAspectRatio="none"><path id="work-path-a" d="M205 145 C300 160 300 250 375 270" /><path id="work-path-b" d="M610 145 C520 165 505 235 430 270" /><path id="work-path-c" d="M430 300 C520 320 540 375 635 390" /><circle r="4"><animateMotion dur="4.8s" repeatCount="indefinite"><mpath href="#work-path-a" /></animateMotion></circle><circle className="signal-blue" r="3"><animateMotion dur="5.7s" repeatCount="indefinite"><mpath href="#work-path-b" /></animateMotion></circle><circle r="4"><animateMotion dur="5.2s" repeatCount="indefinite"><mpath href="#work-path-c" /></animateMotion></circle></svg><AnimatePresence mode="wait"><motion.div animate={{ opacity: 1, scale: 1 }} className={`v3-work-system__scene scene-${active + 1}`} exit={reduceMotion ? undefined : { opacity: 0, scale: .985 }} initial={reduceMotion ? false : { opacity: 0, scale: .985 }} key={step.title} transition={{ duration: .32, ease }}><span className="system-tile tile-a"><small>Input</small><b>{step.nodes[0]}</b><i /></span><span className="system-tile tile-b"><small>System</small><b>{step.nodes[1]}</b><i /></span><span className="system-tile tile-c"><small>Output</small><b>{step.nodes[2]}</b><i /></span><strong className="system-core"><ActiveIcon size={38} /><i /></strong><em><i /> Active system / 0{active + 1}</em></motion.div></AnimatePresence></div>
      <AnimatePresence mode="wait"><motion.aside animate={{ opacity: 1, scale: 1, y: 0 }} id="work-detail" initial={reduceMotion ? false : { opacity: 0, scale: 1.015, y: 8 }} exit={reduceMotion ? undefined : { opacity: 0, scale: .99 }} key={step.title} role="tabpanel" transition={{ duration: .32, ease }}><header><span><ActiveIcon size={18} /></span><small>Active step / 0{active + 1}</small><div className="v3-work-orbit" aria-hidden="true"><i /><i /><i /><b /></div></header><h3>{step.title}</h3><p>{step.description}</p><ul>{step.bullets.map((bullet) => <li key={bullet}><i />{bullet}</li>)}</ul><a href="#contact">Explore our process <ArrowRight size={15} /></a></motion.aside></AnimatePresence>
    </div>
  </div></section>;
}
